In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

In [12]:
a = np.random.randint(10, size=(3, 4))
b = np.random.randint(10, size=(4, 1))

In [13]:
print(a)
print(b)

[[7 1 1 1]
 [7 9 8 2]
 [1 3 8 4]]
[[3]
 [6]
 [1]
 [4]]


In [17]:
a.shape


(3, 4)

In [22]:
b.shape

c = a[:].copy()

In [26]:
c = a.T + b
print(c)
    

[[10 10  4]
 [ 7 15  9]
 [ 2  9  9]
 [ 5  6  8]]


In [28]:
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [34]:
c = a + b.T
print(c)

[[10  7  2  5]
 [10 15  9  6]
 [ 4  9  9  8]]


In [40]:
x = np.random.randint(10, size=(4, 3))
y = np.random.randint(10, size=(3, 1))
z = x*y
print(x)
print(y)
print(z)

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [1]:
import numpy as np

In [3]:
a = np.random.randn(4,3)


In [6]:
b = np.sum(a, axis = 1, keepdims = True)

In [7]:
print(b.shape)


(4, 1)
